#!/bin/bash

set -e
set -x

#mkdir graphite
#cd graphite
sudo apt-get install python-virtualenv python-cairo python-dev
sudo apt-get install git g++

virtualenv env --system-site-packages
source env/bin/activate

mkdir src
mkdir -p data/storage/log/webapp/
mkdir -p data/storage/ceres/

pip install -U pip
pip install -U -r requirements.txt

cd src

git clone https://github.com/graphite-project/graphite-web.git
git clone https://github.com/graphite-project/carbon.git
git clone https://github.com/graphite-project/whisper.git
git clone https://github.com/graphite-project/ceres.git

cd ceres/
pip install -e .

cd ../whisper/
pip install -e .

cd ../carbon
rm -f setup.cfg
pip install -e .

cd ../graphite-web
rm -f setup.cfg
pip install -e .

cd ../..

pip install -e .

mkdir -p data/conf
cp src/carbon/conf/carbon.conf.example data/conf/carbon.conf
cp src/carbon/conf/storage-schemas.conf.example data/conf/storage-schemas.conf

./carbon-cache start

if ! grep -q SECRET_KEY graphite_node/local_settings.py 2>/dev/null; then
    echo "SECRET_KEY = '$(date | md5sum | cut -f 1 -d ' ')'" >> graphite_node/local_settings.py
fi

django-admin.py syncdb --settings=graphite_node.settings
